spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/CT_crm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 666666

#  jpa:
#    show-sql: true

#  jpa:
#    hibernate:
#      ddl-auto: create 